# Jobs #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jobs
  name: jobs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: broken-job
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - command:
        - sleep
        - "2"
        - "&&"
        - echo
        - hello world
        image: busybox:stable
        name: broken-job
        resources: {}
      restartPolicy: OnFailure
  backoffLimit: 5
  activeDeadlineSeconds: 1

# Multi-Containers #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: multicontainers
  name: multicontainers
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainer
  name: multicontainer
  namespace: multicontainers
spec:
  containers:
  - image: busybox:stable
    name: app
    volumeMounts:
      - name: app-shared
        mountPath: /app
    command: ["/bin/sh", "-c"]
    args: ["while true; do date > /app/output.log; sleep 1; done"]
  # - image: busybox:stable
  #   name: sidecar
  #   volumeMounts:
  #   - name: app-shared
  #     mountPath: /app
  #   command: ["/bin/sh", "-c"]
  #   args: ["while true; do cat /app/output.log; sleep 1; done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-shared
      emptyDir: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test-webserver
  labels:
    app: ambassador-test
  namespace: multicontainers
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-test-svc
  namespace: multicontainers
spec:
  selector:
    app: ambassador-test
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: multicontainers
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_backend ambassador_test_svc
    backend ambassador_test_svc
      server svc ambassador-test-svc:8081

---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test
  namespace: multicontainers
spec:
  containers:
  - name: main
    image: radial/busyboxplus:curl
    command: ["sh", "-c", "while true; do curl localhost:8080; sleep 5; done"]
  # - name: ambassador
  #   image: haproxy:2.4
  #   volumeMounts:
  #   - name: config
  #     mountPath: /usr/local/etc/haproxy
  volumes:
  - name: config
    configMap:
      name: haproxy-config

# Init #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: init
  name: init

# Volumes #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: volumes-setup
  name: volumes-setup
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: volumes
  name: volumes
---
# Daemonset is used here to just add a file on each of the worker nodes for the hostPath question. Ideally this would be a "daemonset job" but such a resource doesn't exist
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: create-host-path-data
  namespace: volumes-setup
spec:
  selector:
    matchLabels:
      name: create-host-path-data
  template:
    metadata:
      labels:
        name: create-host-path-data
    spec:
      containers:
      - command: ["sh", "-c", "date > /app/data.log && while true; do sleep 1; done"]
        image: busybox:stable
        name: create-host-path-data
        volumeMounts:
        - name: host-data
          mountPath: /app/data.log
      volumes:
      - name: host-data
        hostPath:
          path: /etc/data.log
          type: FileOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /etc/persistentVol
    type: DirectoryOrCreate

# Deployments #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: deployments
  name: deployments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rolling-deploy
  name: rolling-deploy
  namespace: deployments
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rolling-deploy
  template:
    metadata:
      labels:
        app: rolling-deploy
    spec:
      containers:
      - image: nginx:1.22
        name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-config
  namespace: deployments
data:
  index.html: |
    this is the BLUE deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-config
  namespace: deployments
data:
  index.html: |
    this is the GREEN deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: main-config
  namespace: deployments
data:
  index.html: |
    this is the MAIN deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-config
  namespace: deployments
data:
  index.html: |
    this is the CANARY deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  namespace: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-deploy
      colour: blue
  template:
    metadata:
      labels:
        app: bluegreen-deploy
        colour: blue
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: blue-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
  namespace: deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-deploy
      colour: green
  template:
    metadata:
      labels:
        app: bluegreen-deploy
        colour: green
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: green-config
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-svc
  namespace: deployments
spec:
  selector:
    app: bluegreen-deploy
    colour: blue
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: bluegreen-ingress
  namespace: deployments
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: bluegreen-svc
            port:
              number: 80
        path: /bluegreen
        pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deploy
  namespace: deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-example
      environment: main
  template:
    metadata:
      labels:
        app: canary-example
        environment: main
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: main-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deploy
  namespace: deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-example
      environment: canary
  template:
    metadata:
      labels:
        app: canary-example
        environment: canary
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config
        configMap:
          name: canary-config
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: deployments
spec:
  selector:
    app: canary-example
    environment: main
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: canary-ingress
  namespace: deployments
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: canary-svc
            port:
              number: 80
        path: /canary
        pathType: Prefix

# Monitoring #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: monitoring
  name: monitoring
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cpu-pod
  name: cpu-pod
  namespace: monitoring
spec:
  containers:
  - image: gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.9
    name: resource-container
  - image: radial/busyboxplus:curl
    name: busybox-sidecar
    command: ['/bin/sh', '-c', 'until curl localhost:8080/ConsumeCPU -d "millicores=500&durationSec=3600"; do sleep 5; done && while true; do sleep 10; done']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: failing-pod
  name: failing-pod
  namespace: monitoring
spec:
  containers:
  - image: linuxacademycontent/random-crashing-web-server:1
    name: failing-pod
  - image: radial/busyboxplus:curl
    name: busybox-sidecar
    command: ['/bin/sh', '-c', 'while true; do curl -i http://localhost:8080/ && sleep 1; done']    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: broken-pod
  name: broken-pod
  namespace: monitoring
spec:
  containers:
  - image: nginx:stable.z
    name: broken-pod
    livenessProbe:
      httpGet:
        path: /
        port: 81
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always

# Custom Resource Definitions #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: crds
  name: crds
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beehives.esnow.uk
spec:
  group: esnow.uk
  names:
    kind: BeeHive
    plural: beehives
    singular: beehive
    shortNames:
    - hive
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bees:
                type: integer
              supers:
                type: integer

# Security #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: security
  name: security   
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-broken-sa
  namespace: security
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sa-pod
  name: sa-pod
  namespace: security
spec:
  containers:
  - image: radial/busyboxplus:curl
    name: sa-pod
    command: ['/bin/sh', '-c', 'while true; do curl -s --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST/api/v1/namespaces/security/pods && sleep 1; done']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: my-broken-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-pods-role
  namespace: security
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

# Resources #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: resources
  name: resources
---
apiVersion: v1
kind: Pod
metadata:
  name: running-pod
  namespace: resources
spec:
  containers:
  - name: running-pod
    image: busybox:stable
    command: ["sh", "-c", "while true; do echo 'Running...' sleep 1; done"]
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 100Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-quota
  namespace: resources
spec:
  hard:
    requests.memory: 128Mi
    requests.cpu: 500m
    limits.memory: 256Mi
    limits.cpu: "1"

# Config Maps and Secrets #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: configs
  name: configs
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: configmap-pod
  name: configmap-pod
  namespace: configs
spec:
  containers:
  - image: busybox:stable
    name: configmap-pod
    command: ["/bin/sh", "-c", "while true; do echo $CM_DATA_MESSAGE && cat /data/app.cfg && sleep 1; done"]
    envFrom:
      - configMapRef:
          name: my-configmap
        prefix: CM_DATA_
    volumeMounts:
      - name: my-cm-vol
        mountPath: /data/app.cfg
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: my-cm-vol
      configMap:
        name: my-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: configs
data:
  myapp_message: My message is Hello, World!
  app.cfg: |
    # A config file
    key1=value1
    key2=value2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
  namespace: configs
spec:
  containers:
  - image: busybox:stable
    name: secret-pod
    command: ["sh", "-c", "while true; do sleep 1; done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always

# Network Policies #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: np-test-a
    team: ateam
  name: np-test-a
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: np-test-b
    team: bteam
  name: np-test-b
---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: np-test-a
  labels:
    app: np-test-server
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80

# Services #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: services
  name: services
---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: services
  labels:
    app: nginx-server
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80

# Ingress #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: ingress
  name: ingress
---
---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  namespace: ingress
  labels:
    app: nginx-server
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-svc
  namespace: ingress
spec:
  selector:
    app: nginx-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80