# Jobs #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jobs
  name: jobs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: broken-job
  namespace: jobs
spec:
  template:
    spec:
      containers:
      - command:
        - sleep
        - "2"
        - "&&"
        - echo
        - hello world
        image: busybox:stable
        name: broken-job
        resources: {}
      restartPolicy: OnFailure
  backoffLimit: 5
  activeDeadlineSeconds: 1

# Multi-Containers #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: multicontainers
  name: multicontainers
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainer
  name: multicontainer
  namespace: multicontainers
spec:
  containers:
  - image: busybox:stable
    name: app
    volumeMounts:
      - name: app-shared
        mountPath: /app
    command: ["/bin/sh", "-c"]
    args: ["while true; do date > /app/output.log; sleep 1; done"]
  # - image: busybox:stable
  #   name: sidecar
  #   volumeMounts:
  #   - name: app-shared
  #     mountPath: /app
  #   command: ["/bin/sh", "-c"]
  #   args: ["while true; do cat /app/output.log; sleep 1; done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-shared
      emptyDir: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test-webserver
  labels:
    app: ambassador-test
  namespace: multicontainers
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-test-svc
  namespace: multicontainers
spec:
  selector:
    app: ambassador-test
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: multicontainers
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_backend ambassador_test_svc
    backend ambassador_test_svc
      server svc ambassador-test-svc:8081

---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test
  namespace: multicontainers
spec:
  containers:
  - name: main
    image: radial/busyboxplus:curl
    command: ["sh", "-c", "while true; do curl localhost:8080; sleep 5; done"]
  # - name: ambassador
  #   image: haproxy:2.4
  #   volumeMounts:
  #   - name: config
  #     mountPath: /usr/local/etc/haproxy
  volumes:
  - name: config
    configMap:
      name: haproxy-config

# Init #######################
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: init
  name: init
